spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filmproject
    username: springstudent
    password: springstudent

  application:
    name: film

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
server:
  port: 8080


logging:
  level:
    root: warn
